lists:
  - [А, а]
  - [Б, б]
  - [В, в]
  - [Г, г]
  - [Ґ, ґ]
  - [Д, д]
  - [Е, е]
  - [Є, є]
  - [Ж, ж]
  - [З, з]
  - [И, и]
  - [І, і]
  - [Ї, ї]
  - [Й, й]
  - [К, к]
  - [Л, л]
  - [М, м]
  - [Н, н]
  - [О, о]
  - [П, п]
  - [Р, р]
  - [С, с]
  - [Т, т]
  - [У, у]
  - [Ф, ф]
  - [Х, х]
  - [Ц, ц]
  - [Ч, ч]
  - [Ш, ш]
  - [Щ, щ]
  - [Ь, ь]
  - [Ю, ю]
  - [Я, я]
keyboards:
  - [["~", "'"], ["!", 1], ['"', 2], ["№", 3], [";", 4], ["%", 5], [":", 6], ["&", 7], ["*", 8], ["(", 9], ["_", "-"], ["+", "="]]
  - [[Й, й], [Ц, ц], [У, у], [К, к], [Е, е], [Н, н], [Г, г], [Ш, ш], [Щ, щ], [З, З], [Х, х], [Ї, ї], ["|", "\\"]]
  - [[Ф, ф], [І, і], [В, в], [А, а], [П, п], [Р, р], [О, о], [Л, л], [Д, д], [Ж, ж],[Є, є]]
  - [[Я, я], [Ч, ч], [С, с], [М, м], [И, и], [Т, т], [Ь, ь], [Б, б], [Ю, ю], [",", "."]]
translit:
  - [A, a]
  - [B, b]
  - [V, v]
  - [G, g]
  - [G, G]
  - [D, d]
  - [E, e]
  - [E, E]
  - [Zh, zh]
  - [Z, z]
  - [I, i]
  - [I, I]
  - [Yi, Yi]
  - [Y, y]
  - [K, k]
  - [L, l]
  - [M, m]
  - [N, n]
  - [O, o]
  - [P, p]
  - [R, r]
  - [S, s]
  - [T, t]
  - [U, u]
  - [F, f]
  - [H, h]
  - [Ts, ts]
  - [Ch, ch]
  - [Sh, sh]
  - [Sch, sch]
  - ['', '']
  - [Yu, yu]
  - [Ya, ya]
