lists:
  - [A, a]
  - [B, b]
  - [C, c]
  - [D, d]
  - [E, e]
  - [F, f]
  - [G, g]
  - [H, h]
  - [I, i]
  - [J, j]
  - [K, k]
  - [L, l]
  - [M, m]
  - [N, n]
  - [O, o]
  - [P, p]
  - [Q, q]
  - [R, r]
  - [S, s]
  - [T, t]
  - [U, u]
  - [V, v]
  - [W, w]
  - [X, x]
  - [Y, y]
  - [Z, z]
keyboards:
  - [["~", "`"], ["!", 1], ["@", 2], ["#", 3], ["$", 4], ["%", 5], ["^", 6], ["&", 7], ["*", 8], ["(", 9], ["_", "-"], ["+", "="]]
  - [[Q, q], [W, w], [E, e], [R, r], [T, t], [Y, y], [U, u], [I, i], [O, o], [P, p], ["{", "["], ["}", "]"], ["|", "\\"]]
  - [[A, a], [S, s], [D, d], [F, f], [G, g], [H, h], [J, j], [K, k], [L, l], [":", ";"],['"', "'"]]
  - [[Z, z], [X, x], [C, c], [V, v], [B, b], [N, n], [M, m], ["<",","], [">", "."], ["?", "/"]]